{
 "title": "Application Statistics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Latency",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "limit": 50000,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"pe-hackathon\" && name=~\"GET.*|POST.*|PUT.*|DELETE.*\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"app|loki|prometheus|tempo\"}[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(status_code) (\r\n  count_over_time(\r\n    {job=~\".+\", source=\"application-logs\"}\r\n    | json path=\"path\", status_code=\"status_code\", logger=\"logger\"\r\n    | logger != `werkzeug`\r\n    | status_code !~ `[23][0-9]{2}`\r\n    [1m]\r\n  )\r\n)"
    },
    {
     "direction": "backward",
     "expr": "sum by(level) (count_over_time({job=~\".+\", source=\"application-logs\"} | json level=\"level\" | level !~ `INFO|DEBUG` [1m]))"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "limit": 50000,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"pe-hackathon\" && name=~\"GET.*|POST.*|PUT.*|DELETE.*\"}",
     "tableType": "traces"
    }
   ]
  }
 ]
}