apiVersion: 1

groups:
- name: cpu-usage-alerts
  folder: Production
  interval: 1m

  rules:
  - uid: cpu_usage_high
    title: High CPU Usage (>0.2)
    condition: A
    data:
    - refId: A
      datasourceUid: PBFA97CFB590B2093
      relativeTimeRange:
        from: 300
        to: 0
      model:
        expr: rate(process_cpu_seconds_total{job=~"app|loki|prometheus|tempo"}[1m]) > bool 0.2
        format: time_series
        instant: true
        intervalMs: 1000
        maxDataPoints: 43200
        refId: A
    for: 0s
    labels:
      severity: critical
      alertname: HighCPU
    annotations:
      summary: "CPU usage above 0.2 for job {{ $labels.job }}"
      description: "CPU usage is currently {{ $value }} for {{ $labels.job }}"
    noDataState: NoData
    execErrState: Error
