apiVersion: 1

contactPoints:
- orgId: 1
  name: discord-webhook
  receivers:
  - uid: discord_webhook_receiver
    type: discord
    disableResolveMessage: false
    settings:
      url: ${DISCORD_WEBHOOK_URL}
      title: '{{ template "default.title" . }}'
      message: '{{ template "default.message" . }}'
